branches:
  only:
    - master
sudo: false
language: ruby
rvm:
  - 2.3.3
install: bundle install --jobs=3 --retry=3 && gem install jekyll s3_website
script: jekyll build
after_success: s3_website push
